#!/bin/bash

# change-primary-resolution
# Changes the resolution of the primary display using xrandr
# Usage: ./change-primary-resolution X Y
#  X: Desired horizontal resolution (multiple of 8)
#  Y: Desired vertial resolution

# get primary screen name from xrandr
primary_screen=$(xrandr | grep -E ' connected (primary )?[1-9]+' | sed -e 's/\([A-Z0-9]\+\) connected.*/\1/')

# get mode line from cvt
modeline=$(cvt $1 $2 | sed -n -e 's/^.*Modeline //p')
if [[ "${modeline}" == *usage:* ]] ; then # invalid input to cvt
  echo 'invalid resolution'
  exit 1
fi

# get mode name from modeline
mode_name=$(echo "${modeline}" | sed -n -e 's/^"\(.*\)".*/\1/p')
# convert modeline to array
modeline_arr=($(echo "${modeline}" | sed -n -e 's/"//gp'))

# silence stderr if mode already exists
xrandr --newmode "${modeline_arr[@]}" 2>/dev/null
xrandr --addmode "${primary_screen}" "${mode_name}"
xrandr --output "${primary_screen}" --mode "${mode_name}"
