#!/bin/bash

# change-primary-resolution.sh
# Changes the resolution of the primary display using xrandr
# Usage: ./change-primary-resolution.sh X Y
#  X: Desired horizontal resolution (multiple of 8)
#  Y: Desired vertial resolution

# extract primary screen name from xrandr
primary_screen=$(xrandr | sed -n -e 's/^\(.*\) connected primary.*/\1/p')

# get mode line from cvt
modeline=$(cvt $1 $2 | sed -n -e 's/^.*Modeline //p')
if [[ $modeline == *usage:* ]] ; then # invalid input to cvt
  echo "invalid resolution"
  exit 1
fi

# mode name is in quotes
mode_name=$(echo $modeline | sed -n -e 's/^"\(.*\)".*/\1/p')

# silence stderr if mode already exists
xrandr --newmode $modeline 2> /dev/null
xrandr --addmode $primary_screen $mode_name
xrandr --output $primary_screen --mode $mode_name
