#!/bin/bash
mkdir ~/.emacs.d/
cd ~/.emacs.d/
git init
git remote add origin git@gitlab.ednolan.com:ednolan/emacs-init.git
git pull origin master
eval `opam config env`
opam install tuareg merlin ocp-indent
git clone --recursive https://github.com/Andersbakken/rtags.git
cd rtags
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .
make
