#!/bin/bash

read -p "Hostname: " hostname_in

# Set hostname
echo "${hostname_in}" > /etc/hostname
sed -i -e "2s/ubuntu/${hostname_in}/" /etc/hosts
hostname "${hostname_in}"

# Add ppa for cinnamon and install it
apt-add-repository -y ppa:embrosyn/cinnamon
apt update
apt install -y cinnamon blueberry

# Install packages
apt install -y git emacs opam pioneers openssh-server audacity pianobooster

# Download and install theme files
sudo -u eddie wget -O '/home/eddie/Downloads/Modern-Mint.zip' 'https://dl.opendesktop.org/api/files/download/id/1464717637/174945-Modern%20Mint.zip'
sudo -u eddie unzip '/home/eddie/Downloads/Modern-Mint.zip' -d '/home/eddie/.themes/'
apt install -y adwaita-icon-theme adwaita-icon-theme-full

# Generate ssh key
sudo -u eddie ssh-keygen -t rsa -C 'eddiejnolan@gmail.com'
# Set up git
sudo -u eddie git config --global user.name 'Edward Nolan'
git config --global user.email 'eddiejnolan@gmail.com'

# OCaml
sudo -u eddie `yes | opam init`
sudo -u eddie opam switch 4.03.0

# CMake
apt install cmake

# Python
apt install python-pip python3-tk

# Tex
apt install texlive latexmk

# Semio
sudo -u eddie opam install menhir ppx_sexp_conv ppx_compare ppx_custom_printf ppx_enumerate core ocamlgraph

# Desmond
apt install -y libgtkmm-3.0-dev libsndfile1-dev uuid-dev
