#!/bin/bash

# Set hostname
read -p 'Change hostname?' choice
case "${choice}" in
    y|Y ) {
        read -p "Hostname: " hostname_in
        echo "${hostname_in}" > /etc/hostname
        sed -i -e "2s/ubuntu/${hostname_in}/" /etc/hosts
        hostname "${hostname_in}"
    } ;;
    n|N ) echo 'Not changing hostname';;
    * ) echo 'Invalid choice';;
esac

## Desktop environment/theme

# Add ppa for cinnamon and install it
apt-add-repository -y ppa:embrosyn/cinnamon
apt update
apt install -y cinnamon blueberry

# Adwaita theme
apt install -y adwaita-icon-theme adwaita-icon-theme-full

## Application software

# Audio
apt install -y audacity pianobooster

# Development
apt install -y git emacs

# Utilities
apt install -y gnome-tweak-tool k4dirstat network-manager-openvpn-gnome openssh-server openvpn systemd-coredump tree

# Video games
apt install -y pioneers

## Programming languages/tools

# C++
apt install -y clang libclang-dev exuberant-ctags libgflags-dev libboost-all-dev

# CMake
apt install -y cmake

# Go
apt install -y golang-go

# Mongodb
apt install -y mongodb

# Node.js
curl -sL https://deb.nodesource.com/setup_7.x | bash -
apt-get install -y nodejs

# OCaml
apt install -y opam m4

# Python
apt install -y python-pip python3-tk

# Rust
apt install -y rustc cargo

# Tex
apt install -y texlive latexmk texlive-xetex

## Projects and libraries

# CD player
apt install -y libasound-dev libfftw3-dev

# Desmond
apt install -y libgtkmm-3.0-dev libsndfile1-dev uuid-dev
