#!/bin/bash

# Set hostname
read -p "Hostname: " hostname_in
echo "${hostname_in}" > /etc/hostname
sed -i -e "2s/ubuntu/${hostname_in}/" /etc/hosts
hostname "${hostname_in}"

## Desktop environment/theme

# Add ppa for cinnamon and install it
apt-add-repository -y ppa:embrosyn/cinnamon
apt update
apt install -y cinnamon blueberry

# Adwaita theme
apt install -y adwaita-icon-theme adwaita-icon-theme-full

## Application software

# Audio
apt install -y audacity pianobooster

# Development
apt install -y git emacs opam openssh-server

# Video games
apt install -y pioneers

## Programming languages/tools

# CMake
apt install -y cmake

# Go
apt install -y golang-go

# OCaml
apt install -y opam

# Python
apt install -y python-pip python3-tk

# Rust
apt install -y rustc cargo

# Tex
apt install -y texlive latexmk

## Projects

# Desmond
apt install -y libgtkmm-3.0-dev libsndfile1-dev uuid-dev
